In [1]:
import joblib
import pandas as pd

# Load the final trained model
model = joblib.load("heart_disease_random_forest_model.pkl")

print("Model loaded successfully.")
print("Model type:", type(model))

Model loaded successfully.
Model type: <class 'sklearn.pipeline.Pipeline'>

In [2]:
# Example patient data
patient = pd.DataFrame([{
    "age": 55,
    "sex": 1,
    "chest_pain_type": 4,
    "resting_bp_s": 140,
    "cholesterol": 250,
    "fasting_blood_sugar": 0,
    "resting_ecg": 0,
    "max_heart_rate": 150,
    "exercise_angina": 0,
    "oldpeak": 1.2,
    "ST_slope": 2
}])

print(patient)

   age  sex  chest_pain_type  resting_bp_s  cholesterol  fasting_blood_sugar  \
0   55    1                4           140          250                    0

   resting_ecg  max_heart_rate  exercise_angina  oldpeak  ST_slope
0            0             150                0      1.2         2

In [3]:
# Make prediction
prediction = model.predict(patient)

# Get prediction probability
probability = model.predict_proba(patient)[0, 1]

print("Prediction:", prediction[0])
print(f"Probability of Heart Disease: {probability:.2%}")

if prediction[0] == 1:
    print("Result: Heart Disease")
else:
    print("Result: No Heart Disease")

Prediction: 1.0
Probability of Heart Disease: 74.52%
Result: Heart Disease

In [4]:
# Create a simple prediction summary

result = "Heart Disease" if prediction[0] == 1 else "No Heart Disease"

prediction_summary = pd.DataFrame({
    "Prediction": [result],
    "Heart Disease Probability": [f"{probability:.2%}"]
})

prediction_summary

      Prediction Heart Disease Probability
0  Heart Disease                    74.52%

In [5]:
# Test multiple patients

patients = pd.DataFrame([
    {
        "age": 55,
        "sex": 1,
        "chest_pain_type": 4,
        "resting_bp_s": 140,
        "cholesterol": 250,
        "fasting_blood_sugar": 0,
        "resting_ecg": 0,
        "max_heart_rate": 150,
        "exercise_angina": 0,
        "oldpeak": 1.2,
        "ST_slope": 2
    },
    {
        "age": 40,
        "sex": 0,
        "chest_pain_type": 2,
        "resting_bp_s": 120,
        "cholesterol": 180,
        "fasting_blood_sugar": 0,
        "resting_ecg": 0,
        "max_heart_rate": 170,
        "exercise_angina": 0,
        "oldpeak": 0.2,
        "ST_slope": 2
    }
])

# Predictions
predictions = model.predict(patients)

# Probabilities
probabilities = model.predict_proba(patients)[:, 1]

# Create results table
results = patients[["age", "sex"]].copy()
results["Prediction"] = [
    "Heart Disease" if p == 1 else "No Heart Disease"
    for p in predictions
]
results["Heart Disease Probability"] = [
    f"{p:.2%}" for p in probabilities
]

results

   age  sex        Prediction Heart Disease Probability
0   55    1     Heart Disease                    74.52%
1   40    0  No Heart Disease                    30.61%

In [6]:
# Reusable heart disease prediction function

def predict_heart_disease(
    age,
    sex,
    chest_pain_type,
    resting_bp_s,
    cholesterol,
    fasting_blood_sugar,
    resting_ecg,
    max_heart_rate,
    exercise_angina,
    oldpeak,
    ST_slope
):
    patient_data = pd.DataFrame([{
        "age": age,
        "sex": sex,
        "chest_pain_type": chest_pain_type,
        "resting_bp_s": resting_bp_s,
        "cholesterol": cholesterol,
        "fasting_blood_sugar": fasting_blood_sugar,
        "resting_ecg": resting_ecg,
        "max_heart_rate": max_heart_rate,
        "exercise_angina": exercise_angina,
        "oldpeak": oldpeak,
        "ST_slope": ST_slope
    }])

    prediction = model.predict(patient_data)[0]
    probability = model.predict_proba(patient_data)[0, 1]

    result = "Heart Disease" if prediction == 1 else "No Heart Disease"

    return result, probability

In [7]:
# Test the prediction function

result, probability = predict_heart_disease(
    age=55,
    sex=1,
    chest_pain_type=4,
    resting_bp_s=140,
    cholesterol=250,
    fasting_blood_sugar=0,
    resting_ecg=0,
    max_heart_rate=150,
    exercise_angina=0,
    oldpeak=1.2,
    ST_slope=2
)

print("Prediction:", result)
print(f"Heart Disease Probability: {probability:.2%}")

Prediction: Heart Disease
Heart Disease Probability: 74.52%

In [8]:
# Simple user input interface

print("Heart Disease Prediction")
print("=" * 30)

age = float(input("Age: "))
sex = int(input("Sex (0 = Female, 1 = Male): "))
chest_pain_type = int(input("Chest Pain Type (1-4): "))
resting_bp_s = float(input("Resting Blood Pressure: "))
cholesterol = float(input("Cholesterol: "))
fasting_blood_sugar = int(input("Fasting Blood Sugar (0/1): "))
resting_ecg = int(input("Resting ECG (0-2): "))
max_heart_rate = float(input("Maximum Heart Rate: "))
exercise_angina = int(input("Exercise Angina (0/1): "))
oldpeak = float(input("Oldpeak: "))
ST_slope = int(input("ST Slope (1-3): "))

result, probability = predict_heart_disease(
    age,
    sex,
    chest_pain_type,
    resting_bp_s,
    cholesterol,
    fasting_blood_sugar,
    resting_ecg,
    max_heart_rate,
    exercise_angina,
    oldpeak,
    ST_slope
)

print("\n" + "=" * 30)
print("Prediction:", result)
print(f"Heart Disease Probability: {probability:.2%}")
print("=" * 30)

Heart Disease Prediction
==============================

==============================
Prediction: Heart Disease
Heart Disease Probability: 74.52%
==============================